language: csharp  
sudo: required  
dist: trusty
mono: none
dotnet: 2.0.3
before_script:
  - ./clean.sh -all
script:    
  - ./build.sh
#  - .dotnet\dotnet msbuild src\System.Security.Cryptography.Csp\tests\ /t:BuildAndTest "/p:XunitOptions=-class System.Security.Cryptography.Encryption.Gost3411.Tests.Gost3411CryptoServiceProviderTests" /p:ForceRunTests=true
notifications:
  email:
    on_success: never # default: change
on_failure: change # default: always