# version format
version: 1.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - master
    
# Build worker image (VM template)
image: Visual Studio 2017

# install csp
install:
  - cmd: cspTools\CSPSetup.exe -silent -lang eng -noreboot -nodlg -args "/quiet"
  - ps: Start-Sleep -s 60
  - ps: Restart-Computer -Force
  - ps: Start-Sleep -s 10
  - ps: New-Item -ItemType Directory -Force -Path "$env:LOCALAPPDATA\Crypto Pro"
  - ps: Copy-Item -Force -Recurse ".\cspTools\6d24e911.000" -Destination "$env:LOCALAPPDATA\Crypto Pro\"
  - cmd: '"C:\Program Files\Crypto Pro\CSP\csptest" -absorb -certs -provtype 75 -provider "Crypto-Pro GOST R 34.10-2001 Cryptographic Service Provider" -pattern "6d24e911.000"'
  - cmd: '"C:\Program Files\Crypto Pro\CSP\csptest" -enum -info -type PP_ENUMALGS'

# build script logic
build_script: 
  - clean -all
  - build.cmd  

# disable automatic test discovery, xUnit already runs as part of build.cmd
test: off
  
# runnng specified tests  
test_script:
  - .dotnet\dotnet --info
  - .dotnet\dotnet msbuild src\System.Security.Cryptography.Csp\tests\ /t:BuildAndTest "/p:XunitOptions=-class System.Security.Cryptography.Encryption.Gost3411.Tests.Gost3411CryptoServiceProviderTests" /p:ForceRunTests=true
#  - .dotnet\dotnet msbuild src\System.Security.Cryptography.Csp\tests\ /t:BuildAndTest "/p:XunitOptions=-class System.Security.Cryptography.Encryption.Gost3410.Tests.Gost3410CryptoServiceProviderTests" /p:ForceRunTests=true
#  - .dotnet\dotnet msbuild /t:BuildAndTest src\Common\tests\
#  - .dotnet\dotnet msbuild /t:BuildAndTest src\System.Security.Cryptography.Algorithms\tests\
#  - .dotnet\dotnet msbuild /t:BuildAndTest src\System.Security.Cryptography.Primitives\tests\
#  - .dotnet\dotnet msbuild /t:BuildAndTest src\System.Security.Cryptography.Csp\tests\
#  - .dotnet\dotnet msbuild /t:BuildAndTest src\System.Security.Cryptography.X509Certificates\tests\
#  - .dotnet\dotnet msbuild /t:BuildAndTest src\System.Security.Cryptography.Pkcs\tests\
#  - .dotnet\dotnet msbuild /t:BuildAndTest src\System.Security.Cryptography.Xml\tests\
 
# artifacts on succesfull build 
artifacts:
  - path: artifacts\packages\**\*.nupkg
    name: packages
  - path: artifacts\bin\runtime\netcoreapp-Windows_NT-Debug-x64
    name: runtime
    type: zip
 
# deploy result
deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  provider: GitHub
  auth_token:
    secure: 8tOMOmXZegbWNKbYUtypH+LVj6bj5dYWXbnSPWwWNqZldVnuY+lQQv1r2oFeBMMU # your encrypted token from GitHub
  artifact: packages
  draft: true
  prerelease: true
  on:
    #branch: 
    #  - master                 # release from master branch only
    #  - Fasjeit-auto-build
    appveyor_repo_tag: true        # deploy only on tag push
    
#on_finish:
  # pushing all *.nupkg files in build directory recursively
#- ps: Get-ChildItem "artifacts\packages\**\*.nupkg" | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
#- ps: Get-ChildItem "artifacts\packages\**\symbols\*.nupkg" | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
